# Generated by Django 4.1.7 on 2024-01-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('shoot_location', models.CharField(max_length=255)),
                ('preferred_date', models.DateField()),
                ('additional_requirements', models.TextField()),
            ],
        ),
    ]
